#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.LimCore >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.LimCore=/luci-static/limcore
		set luci.main.mediaurlbase=/luci-static/limcore
		commit luci
	EOF
fi

exit 0
